// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD78GPuI99n7r4u4fdrfCPWX2fmm-_j7_0',
    appId: '1:212617930912:web:682d8d4cef8673f81401c5',
    messagingSenderId: '212617930912',
    projectId: 'todolist-30445',
    authDomain: 'todolist-30445.firebaseapp.com',
    storageBucket: 'todolist-30445.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6JLJGK7hj1vtiREBn4xRAt0P3K1JgKPI',
    appId: '1:212617930912:android:a5888b373e6188511401c5',
    messagingSenderId: '212617930912',
    projectId: 'todolist-30445',
    storageBucket: 'todolist-30445.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6GyFNsTgBnUOFoBY52O60p9AI8ecLO6I',
    appId: '1:212617930912:ios:f43a1589e58ca4051401c5',
    messagingSenderId: '212617930912',
    projectId: 'todolist-30445',
    storageBucket: 'todolist-30445.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6GyFNsTgBnUOFoBY52O60p9AI8ecLO6I',
    appId: '1:212617930912:ios:f43a1589e58ca4051401c5',
    messagingSenderId: '212617930912',
    projectId: 'todolist-30445',
    storageBucket: 'todolist-30445.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD78GPuI99n7r4u4fdrfCPWX2fmm-_j7_0',
    appId: '1:212617930912:web:fd6916355bd088b01401c5',
    messagingSenderId: '212617930912',
    projectId: 'todolist-30445',
    authDomain: 'todolist-30445.firebaseapp.com',
    storageBucket: 'todolist-30445.firebasestorage.app',
  );
}
